networks:
  app:

volumes:
  pgsql-data:
  redis-data:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512m
        reservations:
          memory: 256m

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - /server/.venv
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m
        reservations:
          memory: 128m

  pgsql:
    image: postgres:18-trixie
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgsql-data:/var/lib/postgresql
    networks:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m
        reservations:
          memory: 128m
  redis:
    image: redis:8.6.0-alpine3.23
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST:redis}
      - REDIS_PORT=${REDIS_PORT:6379}
    volumes:
      - redis-data:/data
    networks:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m
        reservations:
          memory: 128m
