networks:
  app:

volumes:
  pgsql-data:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512m
        reservations:
          memory: 256m

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./app:/app
      - /app/.venv
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m
        reservations:
          memory: 128m

  pgsql:
    image: postgres:18-trixie
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgsql-data:/var/lib/postgresql
    networks:
      - app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m
        reservations:
          memory: 128m
